version: "3.8"
services:
  backend:
    build: ./backend
    container_name: astro_backend
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: astro_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
