version: "3.8"
services:
  frontend:
    build: ./frontend   # builds nginx image that serves static files
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - API_KEYS=...   # your backend env
