version: '3.8'
services:
  backend:
    build: ./backend
    container_name: astro-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: astro-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
