version: '3.8'
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      - TWELVEDATA_API_KEY=${TWELVEDATA_API_KEY:-}
      - API_TOKEN=${API_TOKEN:-changeme}
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped
