services:
  backend:
    build: ./backend
    container_name: astro-ict-backend
    env_file: .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: astro-ict-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
