# docker-compose.yml
services:
  backend:
    build:
      context: ./backend
    container_name: astro-ict-backend
    restart: unless-stopped
    environment:
      - TWELVEDATA_APIKEY=${TWELVEDATA_APIKEY:-YOUR_TWELVEDATA_KEY}
      - FINNHUB_KEY=${FINNHUB_KEY:-YOUR_FINNHUB_KEY}
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: astro-ict-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
